### ISSUE TITLE
missing seconds on viz

### ISSUE THREAD

**Issue by ljubo2015** [prelert/kibana-swimlane-vis#15]
Hello this is question or bug i am not sure:
1. I made sub aggregation based on seconds, but this is not shown correctly inside visualization, what i expect to have times with seconds at end but i only have Minutes:
![untitled](https://cloud.githubusercontent.com/assets/15197215/22825406/599c4d52-ef8d-11e6-875f-ce220a924a22.png)

**Comment by peteharverson** [comment]
Thank you for the question. The date format used in the swimlane tooltip had been hardcoded to only display down to seconds (using the MMMM Do YYYY, HH:mm moment.js format). I have now changed this behaviour so that it uses the date format configured in Kibana, using the `dateFormat` setting configured in the Kibana Advanced Settings page under the Management application. This displays down to milliseconds granularity by default (MMMM Do YYYY, HH:mm:ss.SSS). Example shown below:

![image](https://cloud.githubusercontent.com/assets/7405507/25617730/9f66f4a2-2f3b-11e7-8abf-b1cd713f533d.png)

See https://www.elastic.co/guide/en/kibana/current/advanced-options.html for documentation on setting advanced options in Kibana, including `dateFormat`.

This change is in from the v5.3.0 release I added to the Releases page today. Hope this meets your requirements.
