### ISSUE TITLE
[Kibana 5.4] Visualization type of "prealert_swimlane" is invalid 

### ISSUE THREAD

**Issue by tatdatpham** [prelert/kibana-swimlane-vis#22]
Hi, Im trying to install your plugin in kibana 5.4.0. I edited version to 5.4.0 in package.json.
Plugin is installed success. I created Visualization with swimlane but when i search Visualization  or add Visualization (swimlane) i got error :
`Saved Visualization Service: Visualization type of "prealert_swimlane" is invalid. Please change to a valid type.`
Can u help me fix it. Thanks

**P/s: Sorry, i solved my problem**

**Comment by peteharverson** [comment]
Looked like there was a typo in the file name `prealert_swimlane` rather than `prelert_swimlane`. Glad you solved the problem.

When I tried installing into Kibana 5.4.0, I found the swimlane worked as expected, but that it didn't resize as the window was resized. Looked like an issue with webpack loading of the local flot libraries. Do report any other issues you find with 5.4.
