### ISSUE TITLE
Lanes ordered alphabetically with option set to "No" when values are string with numeric values

### ISSUE THREAD

**Issue by acommendador** [prelert/kibana-swimlane-vis#30]
Using v5.5.0. 

For example, the expected order is field 2000 then 1000

PUT test/test/1
{
  "field": "1000",
  "value": 1,
  "time": "2017-07-24T00:00:00"
}
PUT test/test/2
{
  "field": "2000",
  "value": 2,
  "time": "2017-07-24T00:00:00"
}

![image](https://user-images.githubusercontent.com/6619767/28550074-45a56766-707a-11e7-9e76-8449d6c475ba.png)
![image](https://user-images.githubusercontent.com/6619767/28544571-60548f58-705f-11e7-9356-b888e5a5d5ae.png)

Changing the "View by" order does not seem to have an effect.

**Comment by peteharverson** [comment]
Thanks for reporting @acommendador. I have just pushed up a commit which should fix this.

This was happening because I was relying on the ordering of the 'view by' properties in the chart data object built by the visualization being the same as that returned by the elasticsearch aggregation. This assumption on object property order was not valid it appears if the 'view by' values were strings which could be parsed as integers.

Using the same test data as you supplied, with an extra document of
```
PUT test/test/3
{
"field": "101",
"value": 30,
"time": "2017-07-24T00:00:00"
}
```
I now get the expected behaviour, with sort lane option set to 'No':
![image](https://user-images.githubusercontent.com/7405507/28619306-a32d4738-71ff-11e7-9677-c593fac4e65c.png)

and with sort lane option set to 'Descending':
![image](https://user-images.githubusercontent.com/7405507/28619346-d3856cee-71ff-11e7-949e-22da20ef3196.png)

Note for the secondary alphabetical lane ordering, I am now using numeric collation, such that "101" < "1000" < "2000"

This fix will be in the next build for v5.5.1.
