### ISSUE TITLE
Version 6.2.x

### ISSUE THREAD

**Issue by jorgensoares** [prelert/kibana-swimlane-vis#42]
Hello,

Any forecast for the release of the plugin for version 6.2.x?

Thank you!

**Comment by peteharverson** [comment]
Apologies @jorgensoares for the delay in releasing a 6.2.x version. Hopefully some time soon after elasticon. Am hoping to add back in the in-visualization 'Interval' control which had to be dropped for the 6.0 and 6.1 releases. Otherwise it should hopefully just be a case of editing the version number inside the package.json file.

**Comment by jorgensoares** [comment]
Thank you for reply.  Continue the good work! :)

**Comment by peteharverson** [comment]
6.2.0, 6.2.1 and 6.2.2 releases are now available. If you find any issues, please report them.
