### ISSUE TITLE
Build release for 6.3.0

### ISSUE THREAD

**Issue by Evesy** [prelert/kibana-swimlane-vis#44]
Hi,

Would it be possible to build a release for the newly released Kibana 6.3.0 (https://www.elastic.co/blog/kibana-6-3-0-released)?

Cheers,
Mike

**Comment by peteharverson** [comment]
Hi. A few code changes are required due to changes in the Kibana API between 6.2 and 6.3 (usage of Angular Providers, resizing, tooltips, and the colorpicker on the visualization options panel). I'll try and take a look in the next few days and will update this issue with progress.

**Comment by yash199** [comment]
Hi, any update regarding build for 6.3.* !!

Thanks

**Comment by peteharverson** [comment]
Hi. It took a while longer than anticipated to make the code changes to support the changes in the Kibana API between 6.2 and 6.3, but I've just packaged up releases for 6.3.0 and 6.3.1. The distribution now contains the module for the colorpicker used in the options panel, since this was removed from Kibana in 6.3.0.

Please do report any issues you may find, and thanks for your interest in the plugin,
