### ISSUE TITLE
Support for Kibana 6.2.4

### ISSUE THREAD

**Issue by dettmern** [prelert/kibana-swimlane-vis#45]
Any plans to update for Kibana 6.2.4? Much appreciated as this visualization is an enormous help in viewing our daily/weekly ingest status from various sources.

**Comment by peteharverson** [comment]
Hi. Apologies for the delay in packaging up a release for Kibana 6.2.4. I have just packaged up a `6.2.4` release and published it to the releases pages.

The command for installing the 6.2.4 release is:

```
bin/kibana-plugin install https://github.com/prelert/kibana-swimlane-vis/releases/download/v6.2.4/prelert_swimlane_vis-6.2.4.zip
```

I hope to release a version for Kibana 6.3.0 shortly, but this is taking slightly longer than usual as several code changes are required due to changes in the Kibana API between 6.2.x and 6.3.0

Many thanks for your interest in the plugin, and do report any issues you may find.
