### ISSUE TITLE
Support for Kibana v6.4.0

### ISSUE THREAD

**Issue by nikolay** [prelert/kibana-swimlane-vis#48]
Thank you in advance, @peteharverson!

**Comment by peteharverson** [comment]
I hope to have a v6.4.0 release of the swimlane in the next few days. Just need to make a few code edits due to the changes in the Kibana visualization API between 6.3.2 and 6.4.0.

**Comment by peteharverson** [comment]
I have just packaged up a release for Kibana 6.4.0 and published to the releases page.

Note there is a known issue caused by a [bug](https://github.com/elastic/kibana/issues/22868) in Kibana visualizations in Kibana 6.4.0, where updating the aggregation interval using the dropdown above the swimlane does not update the date histogram interval in the sidebar editor when editing the swimlane in the Kibana Visualize tab. The workaround is to use the date histogram interval control in the Visualize sidebar editor to set the aggregation interval before saving the visualization. This should not affect its usage when added to a Kibana dashboard, but please do report any issues you may find.

**Comment by nikolay** [comment]
Thank you very much, @peteharverson!
