### ISSUE TITLE
Kibana v6.4.1 got released

### ISSUE THREAD

**Issue by nikolay** [prelert/kibana-swimlane-vis#49]
@peteharverson Thanks in advance!

**Comment by nikolay** [comment]
By the way, @peteharverson, now that you're part of Elastic, why don't you embed this into Kibana? This will saves us so much frustration waiting for every single plugin to catch up with Kibana's patch release.

**Comment by peteharverson** [comment]
I have just packaged up a release for Kibana 6.4.1 and published to the releases page.

Note the known issue caused by the [bug](https://github.com/elastic/kibana/issues/22868) in Kibana visualizations still affects 6.4.1, where updating the aggregation interval using the dropdown above the swimlane does not update the date histogram interval in the sidebar editor when editing the swimlane in the Kibana Visualize tab. A fix is expected in Kibana 6.4.2.  In the meantime, the workaround is to use the date histogram interval control in the Visualize sidebar editor to set the aggregation interval before saving the visualization.

@nikolay there have been several discussions around adding the swimlane to the core set of visualizations in Kibana. However to date this has not been prioritized, since a similar result can be achieved by using the Kibana Heat Map visualization. I would encourage you to log an issue in the [Kibana GitHub repository](https://github.com/elastic/kibana/issues) with any specific gaps between the Kibana Heat Map and the swimlane that might stop you switching to the Heat Map. Obviously I am biased that there are many use cases where the swimlane provides a simpler and more attractive alternative!

**Comment by nikolay** [comment]
https://github.com/elastic/kibana/issues/23492
