### ISSUE TITLE
Installing swimlane got the kibana server down

### ISSUE THREAD

**Issue by lakshmiral** [prelert/kibana-swimlane-vis#55]
Hi,

I am at 6.6.1 kibana version and was able to install swimlane successfully with --no-optimize on windows. Once the installation is complete, I restarted kibana service and the server was never up. After I remove the plugin and restart server, it works just fine. I made sure to use the compatible version. I also followed the installation steps with kibana directory and installation zip. Any other things I can do to troubleshoot?

**Comment by peteharverson** [comment]
Hi @lakshmiral. Did you see any errors in the server console on start-up with the swimlane plugin installed? Was this the first version you have tried installing, or have you had it working on earlier versions? And just to confirm, what was the command you ran to install the plugin?

**Comment by lakshmiral** [comment]
Hi,
1. It is getting the Kibana server down, I just get an error message that Kibana server is not ready, but if I uninstall swimlane then it works fine.
2. This is the first time we are trying to install swimlane.
3. I have used no-optimize option during installation.
Attached installation steps.
![swimlane installation](https://user-images.githubusercontent.com/48295723/61319154-3ff99900-a7cc-11e9-9e5d-fe7f27abdd5b.PNG)
Any help around this is appreciated!

Thanks!

**Comment by lakshmiral** [comment]
Hi,
Do you suggest any other checkpoints?

**Comment by peteharverson** [comment]
Hi @lakshmiral. I've just installing the swimlane viz plugin on Kibana 6.6.1, using I think the same steps as you, but for me it all seemed to work ok. 

The steps I did were:
- Downloaded Kibana 6.6.1, unzipped and then started up (took around 5 minutes for first time start up)
- Added some data to my Elasticsearch 6.6.1, built a Kibana visualization and dashboard, to confirm all was working OK
- Stopped Kibana
- Installed the swimlane viz with the command:
```
kibana-plugin install https://github.com/prelert/kibana-swimlane-vis/releases/download/v6.6.1/prelert_swimlane_vis-6.6.1.zip --no-optimize
```
- Output from install command showed it had run successfully:
![image](https://user-images.githubusercontent.com/7405507/61472123-bdafd700-a97b-11e9-87e3-d50b6639c584.png)
 
- Restarted Kibana from the `bin` dir with `kibana.bat`
- After a couple of minutes, Kibana had restarted
- Went to Kibana Visualize and was able to use the swimlane viz:
![image](https://user-images.githubusercontent.com/7405507/61472263-ff408200-a97b-11e9-8f7f-c3cf4f119e2e.png)

There are cases reported with Kibana 6.x where the `kibana-plugin install` command seems to stall at the optimizing and caching browser bundles stage - see https://github.com/elastic/kibana/issues/19678.

It might be worth you trying the suggestion [in that issue](https://github.com/elastic/kibana/issues/19678#issuecomment-454462397) to delete `optimize/bundles`. Note the `NODE_OPTIONS="--max-old-space-size=4096"` should only be needed on systems where memory is needed, but you can always apply that too.

Otherwise are you able to try one of the later 7.0 / 7.1 installs of Kibana and the plugin?

**Comment by lakshmiral** [comment]
Hi,
Thanks for your response. I am exactly doing the same installation steps but it is not working on our environment.
I tried the suggestion in the issue, and deleted optimize/bundles and re-installed the plugin but no success.
It mght take few months for our environment to be at 7.X, we are currently planning to upgrade to 6.8 so I might try again once we upgrade. Thanks for your help!

**Comment by peteharverson** [comment]
Thanks for the update @lakshmiral. Sorry you weren't able to get the 6.6.1 install working.
