### ISSUE TITLE
Cannot select "alias" as job elasticsearch index

### ISSUE THREAD

**Issue by ebuildy** [prelert/kibana-swimlane-vis#8]
When "create a new job", I select elasticsearch as data-source, I should be able to select an alias as "index" (especially for time-series indices, alias is wild used).

**Comment by sophiec20** [comment]
(This issue is regarding the core prelert product, not the open source swimlane visualization.)

It is possible to enter an index pattern when creating a new a job. Select **Input index** option, and enter the index pattern in the text box below. e.g. `logstash-*`.

We do not currently support selecting aliases when creating an anomaly detection job. We use the following Indices API (which does not provide alias info) and we use the mappings information provided for the configuration of the job. 

```
curl -XGET 'http://localhost:9200/_all/_mapping'
```

This request has been forwarded to the prelert engineering team at elastic for future consideration.
